"""add appointment magic link fields

Revision ID: b01ec36d68e5
Revises: 02d943e460d4
Create Date: 2026-07-11 22:35:18.789474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01ec36d68e5'
down_revision: Union[str, None] = '02d943e460d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('link_token_hash', sa.String(length=64), nullable=True))
    op.add_column('appointments', sa.Column('link_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'link_expires_at')
    op.drop_column('appointments', 'link_token_hash')
    # ### end Alembic commands ###
