"""add doctor is_general flag

Revision ID: f9c8b78ea6ea
Revises: b01ec36d68e5
Create Date: 2026-07-11 22:43:53.484618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c8b78ea6ea'
down_revision: Union[str, None] = 'b01ec36d68e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_general', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'is_general')
    # ### end Alembic commands ###
